### ISSUE TITLE
Incorrect Default Branch

### ISSUE THREAD

**Issue by MatthewATaylor** [hudson-hybrids/comp-robot-2019#1]
This project's current default branch is **testBranch** and not **master**. This should be changed, but it requires administrator privileges to do so.

**Comment by techguydave** [comment]
Yeah, I noticed that yesterday. I'll take a look at it today.

**Comment by techguydave** [comment]
I made `master` the default branch and also made you an admin of the repo. With great power, yadda yadda.

Closing the issue.
